In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
sns.set(style="whitegrid")

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
df = pd.read_csv("international_debt.csv")

df.head()

,country_name,country_code,indicator_name,indicator_code,debt
0,Afghanistan,AFG,"Disbursements on external debt, long-term (DIS...",DT.DIS.DLXF.CD,72894453.7
1,Afghanistan,AFG,"Interest payments on external debt, long-term ...",DT.INT.DLXF.CD,53239440.1
2,Afghanistan,AFG,"PPG, bilateral (AMT, current US$)",DT.AMT.BLAT.CD,61739336.9
3,Afghanistan,AFG,"PPG, bilateral (DIS, current US$)",DT.DIS.BLAT.CD,49114729.4
4,Afghanistan,AFG,"PPG, bilateral (INT, current US$)",DT.INT.BLAT.CD,39903620.1

In [3]:
df.shape

(2357, 5)

In [4]:
df.columns

Index(['country_name', 'country_code', 'indicator_name', 'indicator_code',
       'debt'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2357 entries, 0 to 2356
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_name    2357 non-null   object
 1   country_code    2357 non-null   object
 2   indicator_name  2357 non-null   object
 3   indicator_code  2357 non-null   object
 4   debt            2357 non-null   float64
dtypes: float64(1), object(4)
memory usage: 92.2+ KB

In [6]:
df.describe()

               debt
count  2.357000e+03
mean   1.306633e+09
std    5.226771e+09
min    0.000000e+00
25%    1.548248e+07
50%    1.073140e+08
75%    5.716575e+08
max    9.621862e+10

In [7]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [8]:
df.isnull().sum()

country_name      0
country_code      0
indicator_name    0
indicator_code    0
debt              0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df['country_name'].nunique()

124

In [18]:
total_debt = df['value'].sum()
print("Total global debt:", total_debt)

KeyError: 'value'

In [19]:
plt.figure(figsize=(10,6))
top_countries.plot(kind='bar', color='skyblue')
plt.title("Top 10 Countries with Highest Debt")
plt.xlabel("Country")
plt.ylabel("Debt Value")
plt.xticks(rotation=45)
plt.show()

NameError: name 'top_countries' is not defined